package com.evan.remindme.data.source.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.evan.remindme.tasks.domain.model.Task;
import com.evan.remindme.sorts.domain.model.Sort;
import com.evan.remindme.settings.domain.model.Setting;

import com.evan.remindme.data.source.dao.TaskDao;
import com.evan.remindme.data.source.dao.SortDao;
import com.evan.remindme.data.source.dao.SettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig sortDaoConfig;
    private final DaoConfig settingDaoConfig;

    private final TaskDao taskDao;
    private final SortDao sortDao;
    private final SettingDao settingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        sortDaoConfig = daoConfigMap.get(SortDao.class).clone();
        sortDaoConfig.initIdentityScope(type);

        settingDaoConfig = daoConfigMap.get(SettingDao.class).clone();
        settingDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        sortDao = new SortDao(sortDaoConfig, this);
        settingDao = new SettingDao(settingDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(Sort.class, sortDao);
        registerDao(Setting.class, settingDao);
    }
    
    public void clear() {
        taskDaoConfig.clearIdentityScope();
        sortDaoConfig.clearIdentityScope();
        settingDaoConfig.clearIdentityScope();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public SortDao getSortDao() {
        return sortDao;
    }

    public SettingDao getSettingDao() {
        return settingDao;
    }

}
