package com.evan.remindme.data.source.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.evan.remindme.tasks.domain.model.Sort;
import com.evan.remindme.tasks.domain.model.Task;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sortDaoConfig;
    private final DaoConfig taskDaoConfig;

    private final SortDao sortDao;
    private final TaskDao taskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sortDaoConfig = daoConfigMap.get(SortDao.class).clone();
        sortDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        sortDao = new SortDao(sortDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);

        registerDao(Sort.class, sortDao);
        registerDao(Task.class, taskDao);
    }
    
    public void clear() {
        sortDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
    }

    public SortDao getSortDao() {
        return sortDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

}
